(() => {
  "use strict";
  const Store = window.EarphoneBdStoreData;
  const role = document.body.dataset.role || "affiliate";
  const roleBn = role === "moderator" ? "মডারেটর" : "অ্যাফিলিয়েট";
  let partner = null;
  let products = [];
  const $ = (id) => document.getElementById(id);
  const els = {
    login: $("loginView"), dashboard: $("dashboardView"), loginForm: $("partnerLoginForm"), code: $("partnerCode"), pin: $("partnerPin"), loginError: $("loginError"), logout: $("logoutButton"),
    welcomeName: $("welcomeName"), welcomeRole: $("welcomeRole"), partnerCodeLabel: $("partnerCodeLabel"), commissionLabel: $("commissionLabel"),
    metricSubmitted: $("metricSubmitted"), metricDelivered: $("metricDelivered"), metricPayable: $("metricPayable"), metricPaid: $("metricPaid"), tabs: $("portalTabs"), panels: [...document.querySelectorAll("[data-panel]")],
    orderForm: $("partnerOrderForm"), product: $("productSelect"), quantity: $("quantity"), district: $("districtSelect"), upazila: $("upazilaSelect"), orderPreview: $("orderPreview"), ordersBody: $("ordersBody"), ordersEmpty: $("ordersEmpty"),
    payoutAvailable: $("payoutAvailable"), payoutForm: $("payoutForm"), payoutsBody: $("payoutsBody"), payoutsEmpty: $("payoutsEmpty"), toast: $("toastWrap")
  };
  const sessionKey = `earphoneBdPartnerSession_${role}`;
  const money = (v) => `৳${Math.round(Number(v)||0).toLocaleString("bn-BD")}`;
  const escapeHTML = (v) => String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  const statusClass = (v) => String(v||"").toLowerCase().replaceAll(" ","-");
  const showToast = (title, text="") => { const t=document.createElement("div"); t.className="toast"; t.innerHTML=`<strong>${escapeHTML(title)}</strong>${text?`<span>${escapeHTML(text)}</span>`:""}`; els.toast.appendChild(t); setTimeout(()=>t.remove(),3200); };
  const partnerOrders = () => Store.getOrders().filter(o => o.partner?.id === partner?.id);
  const partnerPayouts = () => Store.getPayouts().filter(p => p.partnerId === partner?.id);
  const commissionFor = (subtotal) => partner.commissionType === "percent" ? Math.round(subtotal * Number(partner.commissionValue||0) / 100) : Number(partner.commissionValue||0);
  const usedOrderIds = () => new Set(partnerPayouts().filter(p=>p.status!=="Rejected").flatMap(p=>p.orderIds||[]));
  const payableOrders = () => { const used=usedOrderIds(); return partnerOrders().filter(o=>o.status==="Delivered" && !used.has(o.id)); };
  function setLoginState() { const id=sessionStorage.getItem(sessionKey); partner=Store.getPartners().find(p=>p.id===id && p.role===role && p.active!==false) || null; els.login.classList.toggle("hidden",!!partner); els.dashboard.classList.toggle("hidden",!partner); if(partner) renderAll(); }
  function populateLocations(){ const L=window.BangladeshLocations; els.district.innerHTML='<option value="">জেলা নির্বাচন করুন</option>'+L.districts.map(d=>`<option>${escapeHTML(d)}</option>`).join(""); els.district.addEventListener("change",()=>{ const list=L.upazilasFor(els.district.value); els.upazila.disabled=!list.length; els.upazila.innerHTML=list.length?'<option value="">উপজেলা / থানা নির্বাচন করুন</option>'+list.map(u=>`<option>${escapeHTML(u)}</option>`).join(""):'<option value="">আগে জেলা নির্বাচন করুন</option>'; updatePreview(); }); }
  function populateProducts(){ products=Store.getProducts().filter(p=>p.active!==false&&p.available!==false).sort((a,b)=>a.priority-b.priority); els.product.innerHTML='<option value="">পণ্য নির্বাচন করুন</option>'+products.map(p=>`<option value="${p.id}">${escapeHTML(p.name)} · ${escapeHTML(p.color)} · ${money(p.price)}</option>`).join(""); }
  function selectedProduct(){ return products.find(p=>Number(p.id)===Number(els.product.value)); }
  function updatePreview(){ const p=selectedProduct(); const q=Math.max(1,Number(els.quantity.value)||1); const subtotal=p?p.price*q:0; const settings=Store.getSettings(); const delivery=!subtotal?0:(els.district.value==="ঢাকা"?Number(settings.insideDhakaDeliveryFee||0):Number(settings.outsideDhakaDeliveryFee||0)); const commission=commissionFor(subtotal); els.orderPreview.innerHTML=`<div><span>পণ্যের মূল্য</span><strong>${money(subtotal)}</strong></div><div><span>ডেলিভারি</span><strong>${money(delivery)}</strong></div><div><span>আপনার সম্ভাব্য কমিশন</span><strong>${money(commission)}</strong></div><div class="total"><span>কাস্টমারের মোট</span><strong>${money(subtotal+delivery)}</strong></div>`; }
  function renderSummary(){ const orders=partnerOrders(); const payouts=partnerPayouts(); const payable=payableOrders().reduce((s,o)=>s+Number(o.partner?.commissionAmount||0),0); const paid=payouts.filter(p=>p.status==="Paid").reduce((s,p)=>s+Number(p.amount||0),0); els.metricSubmitted.textContent=orders.length.toLocaleString("bn-BD"); els.metricDelivered.textContent=orders.filter(o=>o.status==="Delivered").length.toLocaleString("bn-BD"); els.metricPayable.textContent=money(payable); els.metricPaid.textContent=money(paid); els.payoutAvailable.textContent=money(payable); }
  function renderOrders(){ const rows=[...partnerOrders()].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); els.ordersBody.innerHTML=rows.map(o=>`<tr><td><strong>${escapeHTML(o.id)}</strong><br><small>${new Date(o.createdAt).toLocaleDateString("bn-BD")}</small></td><td>${escapeHTML(o.customer?.name||"")}<br><small>${escapeHTML(o.customer?.phone||"")}</small></td><td>${escapeHTML((o.items||[])[0]?.name||"")} × ${Number((o.items||[])[0]?.quantity||1).toLocaleString("bn-BD")}</td><td>${money(o.totals?.total)}</td><td><span class="status status-${statusClass(o.status)}">${escapeHTML(o.status)}</span></td><td>${money(o.partner?.commissionAmount||0)}</td></tr>`).join(""); els.ordersEmpty.classList.toggle("hidden",rows.length>0); }
  function renderPayouts(){ const rows=[...partnerPayouts()].sort((a,b)=>new Date(b.requestedAt)-new Date(a.requestedAt)); els.payoutsBody.innerHTML=rows.map(p=>`<tr><td><strong>${escapeHTML(p.id)}</strong><br><small>${new Date(p.requestedAt).toLocaleDateString("bn-BD")}</small></td><td>${money(p.amount)}</td><td>${escapeHTML(p.method)}<br><small>${escapeHTML(p.account)}</small></td><td>${(p.orderIds||[]).length.toLocaleString("bn-BD")}টি</td><td><span class="status status-${statusClass(p.status)}">${escapeHTML(p.status)}</span></td></tr>`).join(""); els.payoutsEmpty.classList.toggle("hidden",rows.length>0); }
  function renderAll(){ els.welcomeName.textContent=partner.name; els.welcomeRole.textContent=roleBn; els.partnerCodeLabel.textContent=partner.id; els.commissionLabel.textContent=partner.commissionType==="percent"?`${partner.commissionValue}% কমিশন`:`প্রতি ডেলিভারিতে ${money(partner.commissionValue)}`; populateProducts(); renderSummary(); renderOrders(); renderPayouts(); updatePreview(); }
  function login(e){ e.preventDefault(); const code=els.code.value.trim().toUpperCase(); const pin=els.pin.value.trim(); const found=Store.getPartners().find(p=>p.id.toUpperCase()===code && String(p.pin)===pin && p.role===role && p.active!==false); if(!found){els.loginError.textContent="কোড, PIN অথবা প্যানেলের ধরন সঠিক নয়।";return;} sessionStorage.setItem(sessionKey,found.id); els.loginError.textContent=""; setLoginState(); }
  function submitOrder(e){ e.preventDefault(); const fd=new FormData(els.orderForm); const p=selectedProduct(); if(!p)return; const q=Math.max(1,Number(fd.get("quantity"))||1); const subtotal=p.price*q; const settings=Store.getSettings(); const delivery=fd.get("district")==="ঢাকা"?Number(settings.insideDhakaDeliveryFee||0):Number(settings.outsideDhakaDeliveryFee||0); const commission=commissionFor(subtotal); const id=`${role==="moderator"?"MOD":"AFF"}-${Date.now().toString().slice(-8)}`; const now=new Date().toISOString(); const order={id,createdAt:now,updatedAt:now,customer:{name:fd.get("name"),phone:fd.get("phone"),district:fd.get("district"),upazila:fd.get("upazila"),thana:fd.get("upazila"),address:fd.get("address"),customerNote:fd.get("note")||"",payment:"Cash on Delivery"},items:[{id:p.id,sku:p.sku,slug:p.slug,name:p.name,edition:p.edition,color:p.color,image:p.image,price:p.price,cost:p.cost,quantity:q}],totals:{subtotal,delivery,discount:0,total:subtotal+delivery},status:"Pending",paymentStatus:"Unpaid",source:role,partner:{id:partner.id,role:partner.role,name:partner.name,commissionType:partner.commissionType,commissionValue:partner.commissionValue,commissionAmount:commission},timeline:[{status:"Pending",at:now,note:`${roleBn} প্যানেল থেকে অর্ডার জমা হয়েছে`}],notes:"",courier:"",trackingCode:""}; const orders=Store.getOrders(); orders.push(order); Store.saveOrders(orders); els.orderForm.reset(); els.upazila.disabled=true; els.upazila.innerHTML='<option value="">আগে জেলা নির্বাচন করুন</option>'; updatePreview(); renderAll(); showToast("অর্ডার জমা হয়েছে",id); switchPanel("orders"); }
  function requestPayout(e){ e.preventDefault(); const eligible=payableOrders(); const amount=eligible.reduce((s,o)=>s+Number(o.partner?.commissionAmount||0),0); if(amount<=0){showToast("পেআউট পাওয়া যাচ্ছে না","ডেলিভারড অর্ডারের কমিশন হলে অনুরোধ করতে পারবেন।");return;} const fd=new FormData(els.payoutForm); const payouts=Store.getPayouts(); const request={id:`PAY-${Date.now().toString().slice(-8)}`,partnerId:partner.id,partnerName:partner.name,role:partner.role,amount,method:fd.get("method"),account:fd.get("account"),status:"Requested",orderIds:eligible.map(o=>o.id),requestedAt:new Date().toISOString(),paidAt:"",note:""}; payouts.push(request); Store.savePayouts(payouts); els.payoutForm.reset(); renderAll(); showToast("পেআউট অনুরোধ পাঠানো হয়েছে",money(amount)); }
  function switchPanel(name){ document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab===name)); els.panels.forEach(p=>p.classList.toggle("active",p.dataset.panel===name)); }
  els.loginForm.addEventListener("submit",login); els.logout.addEventListener("click",()=>{sessionStorage.removeItem(sessionKey);partner=null;setLoginState();}); els.tabs.addEventListener("click",e=>{const b=e.target.closest("[data-tab]");if(b)switchPanel(b.dataset.tab);}); els.product.addEventListener("change",updatePreview); els.quantity.addEventListener("input",updatePreview); els.orderForm.addEventListener("submit",submitOrder); els.payoutForm.addEventListener("submit",requestPayout); window.addEventListener("storage",()=>partner&&renderAll()); populateLocations(); setLoginState();
})();
