(() => {
  "use strict";
  const Store=window.EarphoneBdStoreData,$=id=>document.getElementById(id);
  const els={login:$("adminLogin"),app:$("payoutApp"),form:$("payoutLoginForm"),email:$("adminEmail"),password:$("adminPassword"),error:$("adminLoginError"),logout:$("logoutButton"),metrics:$("metrics"),teamOrders:$("teamOrdersBody"),payouts:$("payoutRequestsBody"),partners:$("partnerList"),partnerForm:$("partnerForm"),toast:$("toastWrap"),roleFilter:$("roleFilter"),statusFilter:$("statusFilter")};
  let logged=sessionStorage.getItem("earphoneBdPayoutAdmin")==="1";
  const money=v=>`৳${Math.round(Number(v)||0).toLocaleString("bn-BD")}`; const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); const cls=v=>String(v||"").toLowerCase().replaceAll(" ","-");
  function toast(title,text=""){const t=document.createElement("div");t.className="toast";t.innerHTML=`<strong>${esc(title)}</strong>${text?`<span>${esc(text)}</span>`:""}`;els.toast.appendChild(t);setTimeout(()=>t.remove(),3000)}
  function teamOrders(){return Store.getOrders().filter(o=>["affiliate","moderator"].includes(o.source)||o.partner?.id)}
  function setState(){els.login.classList.toggle("hidden",logged);els.app.classList.toggle("hidden",!logged);if(logged)render()}
  function renderMetrics(){const orders=teamOrders(),payouts=Store.getPayouts();const earned=orders.filter(o=>o.status==="Delivered").reduce((s,o)=>s+Number(o.partner?.commissionAmount||0),0);const requested=payouts.filter(p=>["Requested","Approved"].includes(p.status)).reduce((s,p)=>s+Number(p.amount||0),0);const paid=payouts.filter(p=>p.status==="Paid").reduce((s,p)=>s+Number(p.amount||0),0);els.metrics.innerHTML=[['টিম অর্ডার',orders.length],['মোট কমিশন',money(earned)],['পেন্ডিং পেআউট',money(requested)],['পেমেন্ট হয়েছে',money(paid)]].map(([a,b])=>`<article class="metric"><span>${a}</span><strong>${b}</strong></article>`).join('')}
  function renderOrders(){let rows=teamOrders().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(els.roleFilter.value!=="all")rows=rows.filter(o=>(o.partner?.role||o.source)===els.roleFilter.value);if(els.statusFilter.value!=="all")rows=rows.filter(o=>o.status===els.statusFilter.value);els.teamOrders.innerHTML=rows.map(o=>`<tr><td><strong>${esc(o.id)}</strong><br><small>${new Date(o.createdAt).toLocaleDateString("bn-BD")}</small></td><td>${esc(o.partner?.name||"")}<br><small>${esc(o.partner?.id||"")}</small></td><td>${esc(o.customer?.name||"")}<br><small>${esc(o.customer?.phone||"")}</small></td><td>${money(o.totals?.total)}</td><td>${money(o.partner?.commissionAmount||0)}</td><td><select class="mini-select" data-order-status="${esc(o.id)}">${["Pending","Confirmed","Processing","Shipped","Delivered","Cancelled","Returned"].map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">কোনো টিম অর্ডার পাওয়া যায়নি।</div></td></tr>'}
  function renderPayouts(){const rows=Store.getPayouts().sort((a,b)=>new Date(b.requestedAt)-new Date(a.requestedAt));els.payouts.innerHTML=rows.map(p=>`<tr><td><strong>${esc(p.id)}</strong><br><small>${new Date(p.requestedAt).toLocaleDateString("bn-BD")}</small></td><td>${esc(p.partnerName)}<br><small>${esc(p.partnerId)} · ${esc(p.role)}</small></td><td>${money(p.amount)}</td><td>${esc(p.method)}<br><small>${esc(p.account)}</small></td><td>${(p.orderIds||[]).length.toLocaleString("bn-BD")}টি</td><td><span class="status status-${cls(p.status)}">${esc(p.status)}</span></td><td><div class="row-actions">${p.status!=="Paid"&&p.status!=="Rejected"?`<button class="small-btn primary" data-pay="${esc(p.id)}">Paid</button><button class="small-btn danger" data-reject="${esc(p.id)}">Reject</button>`:""}</div></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">কোনো payout request নেই।</div></td></tr>'}
  function renderPartners(){const rows=Store.getPartners();els.partners.innerHTML=rows.map(p=>`<div class="partner-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.id)} · ${p.role==="affiliate"?"অ্যাফিলিয়েট":"মডারেটর"} · ${esc(p.phone)}</small><small>${p.commissionType==="percent"?`${p.commissionValue}%`:`প্রতি অর্ডার ${money(p.commissionValue)}`} · PIN ${esc(p.pin)}</small></div><div class="row-actions"><button class="small-btn" data-toggle-partner="${esc(p.id)}">${p.active===false?"চালু":"বন্ধ"}</button><button class="small-btn danger" data-delete-partner="${esc(p.id)}">মুছুন</button></div></div>`).join('')}
  function render(){renderMetrics();renderOrders();renderPayouts();renderPartners()}
  function login(e){e.preventDefault();if(els.email.value.trim()==="admin@earphonebd.com"&&els.password.value==="Earphone@2026"){logged=true;sessionStorage.setItem("earphoneBdPayoutAdmin","1");els.error.textContent="";setState()}else els.error.textContent="ইমেইল বা পাসওয়ার্ড সঠিক নয়।"}
  function addPartner(e){e.preventDefault();const fd=new FormData(els.partnerForm),partners=Store.getPartners(),role=fd.get("role");const count=partners.filter(p=>p.role===role).length+1;const id=`${role==="affiliate"?"AFF":"MOD"}${String(count).padStart(3,"0")}`;partners.push({id,role,name:fd.get("name"),phone:fd.get("phone"),pin:fd.get("pin"),commissionType:fd.get("commissionType"),commissionValue:Number(fd.get("commissionValue"))||0,active:true,joinedAt:new Date().toISOString()});Store.savePartners(partners);els.partnerForm.reset();render();toast("টিম সদস্য তৈরি হয়েছে",id)}
  els.form.addEventListener("submit",login);els.logout.addEventListener("click",()=>{logged=false;sessionStorage.removeItem("earphoneBdPayoutAdmin");setState()});els.partnerForm.addEventListener("submit",addPartner);els.roleFilter.addEventListener("change",renderOrders);els.statusFilter.addEventListener("change",renderOrders);
  document.addEventListener("change",e=>{const s=e.target.closest("[data-order-status]");if(!s)return;const orders=Store.getOrders(),o=orders.find(x=>x.id===s.dataset.orderStatus);if(!o)return;o.status=s.value;o.updatedAt=new Date().toISOString();o.timeline=[...(o.timeline||[]),{status:s.value,at:o.updatedAt,note:"Payout dashboard থেকে আপডেট"}];Store.saveOrders(orders);render();toast("অর্ডার স্ট্যাটাস আপডেট হয়েছে",o.id)});
  document.addEventListener("click",e=>{const pay=e.target.closest("[data-pay]"),reject=e.target.closest("[data-reject]"),toggle=e.target.closest("[data-toggle-partner]"),del=e.target.closest("[data-delete-partner]");if(pay||reject){const payouts=Store.getPayouts(),p=payouts.find(x=>x.id===(pay?.dataset.pay||reject?.dataset.reject));if(!p)return;p.status=pay?"Paid":"Rejected";p.paidAt=pay?new Date().toISOString():"";Store.savePayouts(payouts);render();toast(pay?"পেমেন্ট সম্পন্ন":"অনুরোধ বাতিল",p.id)}if(toggle){const partners=Store.getPartners(),p=partners.find(x=>x.id===toggle.dataset.togglePartner);if(p){p.active=p.active===false;Store.savePartners(partners);render()}}if(del){let partners=Store.getPartners();if(confirm("এই সদস্যকে মুছে ফেলবেন?")){partners=partners.filter(x=>x.id!==del.dataset.deletePartner);Store.savePartners(partners);render()}}});window.addEventListener("storage",()=>logged&&render());setState();
})();
